# JBoss WildFly with openshift.KUBE_PING impl and examples.
# Name: 10.245.2.2:5000/dward/wildfly-openshift-examples:v1

FROM 10.245.2.2:5000/dward/wildfly-openshift:v1

#USER root

#ADD standalone-openshif.xml /opt/jboss/wildfly/standalone/configuration/standalone-openshif.xml
#RUN chown jboss:jboss /opt/jboss/wildfly/standalone/configuration/standalone-openshif.xml

#ADD basic-app-cache.war /opt/jboss/wildfly/standalone/deployments/basic-app-cache.war
#RUN chown jboss:jboss /opt/jboss/wildfly/standalone/deployments/basic-app-cache.war

#ADD basic-web-session.war /opt/jboss/wildfly/standalone/deployments/basic-web-session.war
#RUN chown jboss:jboss /opt/jboss/wildfly/standalone/deployments/basic-web-session.war

#ADD hello-servlet.war /opt/jboss/wildfly/standalone/deployments/hello-servlet.war
#RUN chown jboss:jboss /opt/jboss/wildfly/standalone/deployments/hello-servlet.war

#USER jboss
