name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
permissions:
  contents: read
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        # Keep this list as: all supported LTS JDKs, the latest GA JDK, and optionally the latest EA JDK (if available).
        # Reference: https://adoptium.net/support/
        java:
          - 11
          - 17
          - 21
          - 25
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress clean verify
